// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxlHbD8bMys2nXTNlOpyCRWAadCJugnfQ',
    appId: '1:152855688812:web:26e54885e0d6eb607f0a49',
    messagingSenderId: '152855688812',
    projectId: 'marketpointappi',
    authDomain: 'marketpointappi.firebaseapp.com',
    storageBucket: 'marketpointappi.appspot.com',
    measurementId: 'G-VB46R3J70T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSKwJH5HtwnBd_alh_PpMuV2PGdbN5OJ8',
    appId: '1:152855688812:android:dd2a8dc77121f5eb7f0a49',
    messagingSenderId: '152855688812',
    projectId: 'marketpointappi',
    storageBucket: 'marketpointappi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfgZbe-5s-X4PSG6nyER048yCvGm6u-hg',
    appId: '1:152855688812:ios:f33a729c74e61b917f0a49',
    messagingSenderId: '152855688812',
    projectId: 'marketpointappi',
    storageBucket: 'marketpointappi.appspot.com',
    androidClientId: '152855688812-093dvee1bdfg1kididujapsrsmtt6igv.apps.googleusercontent.com',
    iosClientId: '152855688812-2kt52hipcmkld4mq5dqnhk4nfl62q0jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.etfiPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfgZbe-5s-X4PSG6nyER048yCvGm6u-hg',
    appId: '1:152855688812:ios:bef78ec9d35eb6827f0a49',
    messagingSenderId: '152855688812',
    projectId: 'marketpointappi',
    storageBucket: 'marketpointappi.appspot.com',
    androidClientId: '152855688812-093dvee1bdfg1kididujapsrsmtt6igv.apps.googleusercontent.com',
    iosClientId: '152855688812-v52kii4mjen42rpipfkumj0uv4gedr5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.etfiPoint.RunnerTests',
  );
}
